# Generated by Django 6.0.6 on 2026-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="expired_at",
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("waiting", "Waiting"),
                    ("closed", "Closed"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
